# Generated by Django 5.1.1 on 2024-09-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=30)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
